# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WTF is PGP?
email: drew@drewstokes.com
description: > # this means to ignore newlines until "baseurl:"
  Pretty Good Privacy (PGP) is a computer program and
  standard (OpenPGP) for encrypting, decrypting and signing data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pgp.wtf" # the base hostname & protocol for your site
twitter_username: drew_stokes
github_username:  dstokes

# Build settings
markdown: kramdown
